
version: 2

models:
  - name: tb_10_compradores
    description: "retorna os top 10 compradores da base de dados"
    columns:
      - name: vendas_totais
        description: "vendas totais por comprador"
        tests:
          - nao_negativo
          - not_null
      - name: comissao
        description: "comissao por comprador"
        tests:
          - nao_negativo
          - not_null
